modified medical_center design
SpringBoardRepo/sql-ddl_design pull request #1
Opened 2021-05-25 21:59 UTC by poorvarathore05

2021-05-26 20:20 UTC, montrealist requested changes

2021-05-26 20:20 UTC, montrealist commented on Medical_center (2).sql
>  CREATE TABLE "Diseases" (
please make the table names consistent - no capitals.

2021-05-26 20:20 UTC, montrealist commented on Medical_center (2).sql
> +    Speciality TEXT
Some column names are in double quotes, others not - is this intentional?

2021-05-26 20:20 UTC, montrealist commented on Medical_center (2).sql
> +CREATE TABLE diagonesd (
This table name is misspelled. I suggest `diagnoses`.

2021-05-26 20:20 UTC, montrealist commented on Medical_center (2).sql
> +    diagonesd_id Foreign Key
Column name is misspelled. I suggest `diagnosis_id`

2021-05-26 20:20 UTC, montrealist commented on Medical_center (2).sql
>  CREATE TABLE "patients_name" (
Table name stores more than a patient's name - please rename to be more general, for example `patients`.

2021-05-26 20:20 UTC, montrealist commented on Medical_center (2).sql
> +    "Doctor_name" Text   NOT NULL,
What if the same doctor works in more than one medical center? Not sure about what the requirements state, but worth checking.

2021-05-26 20:20 UTC, montrealist commented on Medical_center (2).sql
> +    dis_id Foreign Key
This looks like a table linking diagnoses with visits; in this case it's missing another foreign key.

2021-06-02 13:23 UTC, montrealist commented
Hi Poorva, will you be addressing the changes that I proposed in my comments above?

2021-06-02 17:29 UTC, poorvarathore05 commented
Hi Max,
Yes I just did changes.

2021-06-02 17:44 UTC, poorvarathore05 commented
Hi Max,
Yes, I just made changes on that file.

2021-06-06 17:35 UTC, montrealist commented on outer_space.sql
>    (name, orbital_period_in_years, orbits_around, galaxy_id, moons)
Since you changed it to be a number, the first column in the table is no longer a `name`, but rather `planet_id` I suppose.

2021-06-06 17:37 UTC, montrealist commented on outer_space.sql
> +                   ('{}',3),('{"Naiad", "Thalassa", "Despina", "Galatea", "Larissa", "S/2004 N 1", "Proteus", "Triton", "Nereid", "Halimede", "Sao", "Laomedeia", "Psamathe", "Neso"}',4),
I would insert each moon as a distinct row. I guess it's optional because each moon will only be around one planet, this is just a note for the sake of clean database design.

2021-06-06 17:39 UTC, montrealist commented on outer_space.sql
>    galaxy_name TEXT NOT NULL
The changes to `outer_space.sql` in this pull request are different from the changes you introduced earlier (which I included in my example pull request): https://github.com/montrealist/data-modeling-exercise-example/pull/1/files#diff-084d525d744a7653908cfb771c7d87175d45af4149b0669e311b75d5fe701de4

Why is that?

2021-06-06 17:39 UTC, montrealist approved these changes

2021-06-06 18:31 UTC, merged